namespace JobApplicationManagement.Application.Features.Jobs.DTOs;

/// <summary>
/// Data Transfer Object carrying the client-supplied data required to create a Job.
/// Intentionally excludes:
///   - Id        → server-generated by the database
///   - IsActive  → server-controlled; defaults to true on creation (assumption #1)
/// </summary>
public class CreateJobDto
{
    /// <summary>The job posting title. Required. Max 200 characters.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Detailed description of the role. Required. Max 5000 characters.</summary>
    public string Description { get; set; } = string.Empty;
}
